name: CD

on:
  workflow_dispatch:

concurrency:
  group: CD
  cancel-in-progress: true

jobs:
  staging:
    name: Deploy to Staging
    environment: staging
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up python and poetry
        uses: ./.github/actions/setup

      - name: Publish to TestPyPI
        run: |
          poetry config repository.testpypi https://test.pypi.org/legacy/
          poetry publish --username __token__ --password ${{ secrets.API_TOKEN }} --repository testpypi --build

  production:
    name: Deploy to Production
    environment: production
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up python and poetry
        uses: ./.github/actions/setup

      - name: Publish to PyPI
        run: poetry publish --username __token__ --password ${{ secrets.API_TOKEN }} --build