name: CD

on:
  workflow_dispatch:

concurrency:
  group: CD
  cancel-in-progress: true

jobs:
  production:
    name: Deploy to Production
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up python and poetry
        uses: ./.github/actions/setup
        with:
          python-version: 3.10

      - name: Publish to PyPI
        run: poetry publish --username __token__ --password ${{ secrets.API_TOKEN }} --build