name: CI

on:
  push:
    branches:
      - main
      - release/*

  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: CI
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up python and poetry
        uses: ./.github/actions/setup

      - name: Run tests
        run: poetry run pytest