name: STAGING

on:
  workflow_dispatch:

concurrency:
  group: STAGING
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.x

      - name: Set up poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ./**/.venv
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Run build
        run: poetry build

      - name: Publish to TestPyPI
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
          POETRY_REPOSITORIES_TEST_PYPI: https://test.pypi.org/legacy/
        run: poetry publish --repository test-pypi